version: '2.1'
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: foreign_currency
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-pdev", "-h", "localhost"]
      timeout: 20s
      retries: 10
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    # ports from container exposed to the docker machine and the guest machine
    ports:
      - "7001:7001"
    # Link to containers in another service
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
  
  